name: CI

on: [ push, pull_request ]

# Note: As of now the strategy property is not supported when using reusable workflows, so we can't use a build
# matrix to create the different build cases (see https://docs.github.com/en/actions/using-workflows/reusing-workflows#limitations)
jobs:
    build_1_5_634:
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "v1.5.634"
            docker_version: '0'
            publish: false
            update_latest: false
            platforms: "linux/amd64,linux/arm64"
    build_latest:
        uses: ./.github/workflows/build_and_publish.yml
        with:
            mumble_version: "latest"
            docker_version: '0'
            publish: false
            update_latest: false
            platforms: "linux/amd64,linux/arm64"
